### ISSUE TITLE
SyntaxError: keyword argument repeated

### ISSUE THREAD

**Issue by Monicakcl** [nbraingroup/fmridenoise#21]
When running setup.py I receive the following error message:

  File "setup.py", line 21
    name="fmridenoise",
    ^
SyntaxError: keyword argument repeated

Might be user error on my part (sorry if so!), but it looks like this might also be an issue for users with python 2.4 and 2.6: https://nick.zoic.org/art/syntax-error-keyword-argument-repeated/

**Comment by SiegfriedWagner** [comment]
This package is intended to be used with python 3 only. I will specify this
in README.md
