### ISSUE TITLE
KeyError: 'session'

### ISSUE THREAD

**Issue by kfinc** [nbraingroup/fmridenoise#25]
`BidsGrabber` is looking by default for `session` entity in BIDS structure. It should be adapted to other alternatives of BIDS data organization. That's an issue raised by @jshino via Neurostars:
https://neurostars.org/t/confounds-from-fmriprep-which-one-would-you-use-for-glm/326/43.
The `KeyError: 'session'` appears in a first crash file he sent.

**Comment by SiegfriedWagner** [comment]
Let me clarify the problem - Is `BidsGrabber` failing when there is no `ses` folders in bids files structure?

**Comment by kfinc** [comment]
yes

**Comment by SiegfriedWagner** [comment]
@kbonna can you fix this or should i fix this in next week?

**Comment by kfinc** [comment]
I can try to fix this tomorrow.

**Comment by jshino-git** [comment]
Hi, all
I am @Jshino raised an issue via Neurostars:
https://neurostars.org/t/confounds-from-fmriprep-which-one-would-you-use-for-glm/326/43

I attached data tree (PDF).
[tree.pdf](https://github.com/nbraingroup/fmridenoise/files/3572438/tree.pdf)

Thanks a lot!

**Comment by jshino-git** [comment]
Sorry, I couldn't understand tree...
The tree is
jshino@ubuntu:~/BIDS2$ tree
.
├── dataset_description.json
├── derivatives
│   ├── fmridenoise
│   └── fmriprep
│       ├── dataset_description.json
│       ├── logs
│       │   ├── CITATION.bib
│       │   ├── CITATION.html
│       │   ├── CITATION.md
│       │   └── CITATION.tex
│       ├── sub-08
│       │   ├── anat
│       │   │   ├── sub-08_desc-brain_mask.json
│       │   │   ├── sub-08_desc-brain_mask.nii.gz
│       │   │   ├── sub-08_desc-preproc_T1w.json
│       │   │   ├── sub-08_desc-preproc_T1w.nii.gz
│       │   │   ├── sub-08_dseg.nii.gz
│       │   │   ├── sub-08_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
│       │   │   ├── sub-08_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5
│       │   │   ├── sub-08_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
│       │   │   ├── sub-08_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5
│       │   │   ├── sub-08_from-orig_to-T1w_mode-image_xfm.txt
│       │   │   ├── sub-08_label-CSF_probseg.nii.gz
│       │   │   ├── sub-08_label-GM_probseg.nii.gz
│       │   │   ├── sub-08_label-WM_probseg.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_desc-brain_mask.json
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_desc-preproc_T1w.json
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_dseg.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin6Asym_desc-brain_mask.json
│       │   │   ├── sub-08_space-MNI152NLin6Asym_desc-brain_mask.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin6Asym_desc-preproc_T1w.json
│       │   │   ├── sub-08_space-MNI152NLin6Asym_desc-preproc_T1w.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin6Asym_dseg.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin6Asym_label-CSF_probseg.nii.gz
│       │   │   ├── sub-08_space-MNI152NLin6Asym_label-GM_probseg.nii.gz
│       │   │   └── sub-08_space-MNI152NLin6Asym_label-WM_probseg.nii.gz
│       │   ├── figures
│       │   │   ├── sub-08_dseg.svg
│       │   │   ├── sub-08_space-MNI152NLin2009cAsym_T1w.svg
│       │   │   ├── sub-08_space-MNI152NLin6Asym_T1w.svg
│       │   │   ├── sub-08_task-tapping_desc-aroma_bold.svg
│       │   │   ├── sub-08_task-tapping_desc-carpetplot_bold.svg
│       │   │   ├── sub-08_task-tapping_desc-compcorvar_bold.svg
│       │   │   ├── sub-08_task-tapping_desc-confoundcorr_bold.svg
│       │   │   ├── sub-08_task-tapping_desc-flirtbbr_bold.svg
│       │   │   ├── sub-08_task-tapping_desc-rois_bold.svg
│       │   │   └── sub-08_task-tapping_desc-sdc_bold.svg
│       │   └── func
│       │       ├── sub-08_task-tapping_AROMAnoiseICs.csv
│       │       ├── sub-08_task-tapping_desc-MELODIC_mixing.tsv
│       │       ├── sub-08_task-tapping_desc-confounds_regressors.json
│       │       ├── sub-08_task-tapping_desc-confounds_regressors.tsv
│       │       ├── sub-08_task-tapping_space-MNI152NLin2009cAsym_boldref.nii.gz
│       │       ├── sub-08_task-tapping_space-MNI152NLin2009cAsym_desc-brain_mask.json
│       │       ├── sub-08_task-tapping_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│       │       ├── sub-08_task-tapping_space-MNI152NLin2009cAsym_desc-preproc_bold.json
│       │       ├── sub-08_task-tapping_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
│       │       ├── sub-08_task-tapping_space-MNI152NLin2009cAsym_desc-smoothAROMAnonaggr_bold.nii.gz
│       │       ├── sub-08_task-tapping_space-MNI152NLin6Asym_boldref.nii.gz
│       │       ├── sub-08_task-tapping_space-MNI152NLin6Asym_desc-brain_mask.json
│       │       ├── sub-08_task-tapping_space-MNI152NLin6Asym_desc-brain_mask.nii.gz
│       │       ├── sub-08_task-tapping_space-MNI152NLin6Asym_desc-preproc_bold.json
│       │       ├── sub-08_task-tapping_space-MNI152NLin6Asym_desc-preproc_bold.nii.gz
│       │       ├── sub-08_task-tapping_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.nii.gz
│       │       ├── sub-08_task-tapping_space-T1w_boldref.nii.gz
│       │       ├── sub-08_task-tapping_space-T1w_desc-brain_mask.json
│       │       ├── sub-08_task-tapping_space-T1w_desc-brain_mask.nii.gz
│       │       ├── sub-08_task-tapping_space-T1w_desc-preproc_bold.json
│       │       └── sub-08_task-tapping_space-T1w_desc-preproc_bold.nii.gz
│       └── sub-08.html
├── sub-08
│   ├── anat
│   │   └── sub-08_T1w.nii
│   ├── fmap
│   │   ├── sub-08_magnitude1.nii
│   │   ├── sub-08_magnitude2.nii
│   │   ├── sub-08_phase1.json
│   │   ├── sub-08_phase1.nii
│   │   ├── sub-08_phase2.json
│   │   └── sub-08_phase2.nii
│   └── func
│       └── sub-08_task-tapping_bold.nii
└── task-tapping_bold.json

12 directories, 76 files

**Comment by kbonna** [comment]
I fixed BIDSGrabber interface, it should work now. Please test it and let me know.

**Comment by jshino-git** [comment]
Hi @kbonna ! Thank you very much! I installed `fmridenoise` via `python setup.py install --user`.
Unfortunately, BidsGrabber errors occurred.

The errors were (a .txt file):
https://www.sugarsync.com/pf/D720540_08778893_7765811

You can download a crashfile (.pklz) via
https://www.sugarsync.com/pf/D720540_08778893_7765876

Thanks a lot!

**Comment by kbonna** [comment]
@jshino-git  
Preprocessed files in different spaces caused this problem. I just fixed that adding space filter to query BIDSLayout. Could you try pulling newest version of fmridenoise (from github) and try running it again on your data? If the problem remains, please post the error.

**Comment by jshino-git** [comment]
@kbonna 
Hi! Thank you for your fast reply. I pulled the newest version from github, and installed fmridenoise via `python setup.py install --user`.
Now, `QualityMeasures failed` Errors occurred.

The errors were (an ErrorMessage2.txt file):
https://www.sugarsync.com/pf/D720540_08778893_7768008

The `tree` was (a tree2.txt file)
https://www.sugarsync.com/pf/D720540_08778893_7768018

The crash files were (a crash2.zip file)
https://www.sugarsync.com/pf/D720540_08778893_7768025

Thanks a lot!

**Comment by kbonna** [comment]
Looking on the error, something that I suspected occurred. Since most quality measures rely on computing between-subject correlations with movement, minimum number of n=2 subjects is required to get any values (hence ValueError: x and y must have length at least 2.). I can imagine that some users would still want to run different denoising pipelines for single subject and just inspect density plots for connection strengths, so we should probability handle this exception. @kfinc @SiegfriedWagner  what do you think? 

@jshino-git for now, try running fmridenoise on at least 2 subjects, and you should get preprocessed data and the result reports.

**Comment by SiegfriedWagner** [comment]
It has to be handled on way or another - end users don't like to have a face slap from python unhandled exception.
Either we can add some sanity check code at the very beginning of fmridenoise in [fmridenoise/__main__.py](https://github.com/nbraingroup/fmridenoise/blob/master/fmridenoise/__main__.py) that will prevent users from running on one subject/one pipeline.
Alternatively (or additionally) we can provide way for running fmridenoise with on any number of subjects/pipelines and functionality (within pipeline quality measures and between pipeline quality measures) will depend on user input.

For now I would just add sanity check and then extra functionality later.

**Comment by kfinc** [comment]
I think the problem will be solved when we separate the denoising and quality measures into two connected workflows. This will enable the user to specify if he/she wants only to denoise the data (with denoising and quality measures as default) or run the whole pipeline. In case of trying to run `fmridenoise` on 1 subjects, the workflow will stop after the denoising. For now, even if @jshino-git got the error when running `QualityMeasures` interface, denoised data should already be moved to `fmridenoise` output folder. Nevertheless, I'll add a relevant exception.

**Comment by kbonna** [comment]
All right, we can easily do this modifying BIDSGrab interface to output flag if quality measures should run or not depending on the number of subjects (along with information for the user). That would not crash entire workflow and still provide denoised files.

**Comment by jshino-git** [comment]
@kfinc 
@SiegfriedWagner 
@kbonna 
fmridenoise run completely!
Could you tell me references about fmridenoise, and how should I cite fmridenoise?
Many thanks.

**Comment by kfinc** [comment]
Great @jshino-git ! Thank you so much for your feedback and patience.
For now, you can cite fMRIDenoise Zenodo entry:

Finc, K., Chojnowski, M., Bonna, K., (2019). fMRIDenoise: automated denoising, denoising strategies comparison, and functional connectivity data quality control. Zenodo: DOI 10.5281/zenodo.3236245

**Comment by jshino-git** [comment]
@kfinc Thank you so much!
Could you tell me about the derivatives of fMRIDenoise? Under fmridenoise directory, there are many files, but I cannot understand. For example, `sub-01_task_run-1_..._denoised_pipleline-24HMP_8Phys_SpikeReg.nii.gz` etc.
Is there a tutorial?

**Comment by kfinc** [comment]
@jshino-git, we will add a tutorial soon. The project is very fresh, so we still need some time and help to make it elegant and easy to use.

The only `*.nii.gz` files in your output folder are the fMRI data after applying various denoising pipelines. File `*conn_mat.npy` is a correlation matrix for Schaefer parcellation (200 parcels). File `*.tsv` is a data frame with all nuisance regressors included in denoising for a given pipeline.

**Comment by jandrushko** [comment]
has there been any progress on tutorials and fixing some of these issues? i still have problems with the bidsgrabber and a tutorial would be very helpful. I have longitudinal data I am trying to run this on, which means I have registered my T1w to a midpoint template and have ses-1 and ses-2 in my directory tree

sub-0##
     ses-1
                anat
                fmap
                func
                        run-1.....nii.gz
                        run-2.....nii.gz
     ses-2
                anat
                fmap
                func
                        run-1.....nii.gz
                        run-2.....nii.gz

**Comment by ortiztudelaJ** [comment]
Hi there, 

I am getting this "KeyError: 'session' error as well. Even with a minimalist call and with a very standard structure: 2 tasks with 2 runs each and no sessions identifier.

Any idea on how to fix this?

Javier. 
`python3 -m fmridenoise \
/path/to/BIDS \
-d /path/to/preproc_data/fmriprep/ \
-sub 101 102 \
-g \`


> (...) Storing result file without outputs
200701-15:45:35,753 nipype.workflow WARNING:
	 [Node] Error on "fmridenoise_wf.ConfPrep" (/tmp/fmridenoise/fmridenoise_wf/_pipeline_path_..home..javier...local..lib..python3.6..site-packages..fmridenoise..pipelines..pipeline-ICA-AROMA_8Phys_4GS.json/ConfPrep)
200701-15:45:35,754 nipype.utils DEBUG:
	 Loading pkl: /tmp/fmridenoise/fmridenoise_wf/_pipeline_path_..home..javier...local..lib..python3.6..site-packages..fmridenoise..pipelines..pipeline-ICA-AROMA_8Phys_4GS.json/ConfPrep/result_ConfPrep.pklz
200701-15:45:35,754 nipype.workflow ERROR:
	 Node ConfPrep.a6 failed to run on host EPU4039.
200701-15:45:35,754 nipype.workflow ERROR:
	 Saving crash info to /media/javier/Data/home_office/Jacobs/jacobs_OLM/scripts/preproc/crash-20200701-154535-javier-ConfPrep.a6-2ffa09ba-edd6-4b33-89ac-ed4b289d4b9d.pklz
Traceback (most recent call last):
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 46, in run
    node.run(updatehash=updatehash)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1386, in _run_interface
    self.config["execution"]["stop_on_first_crash"]
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1250, in _collate_results
    for i, nresult, err in nodes:
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/home/javier/.local/lib/python3.6/site-packages/fmridenoise/interfaces/confounds.py", line 84, in _run_interface
    "session": [self.inputs.entities['session']],
KeyError: 'session'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/javier/.local/lib/python3.6/site-packages/fmridenoise/__main__.py", line 168, in <module>
    main()
  File "/home/javier/.local/lib/python3.6/site-packages/fmridenoise/__main__.py", line 164, in main
    workflow.run()
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 46, in run
    node.run(updatehash=updatehash)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1386, in _run_interface
    self.config["execution"]["stop_on_first_crash"]
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1250, in _collate_results
    for i, nresult, err in nodes:
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/javier/.local/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/home/javier/.local/lib/python3.6/site-packages/fmridenoise/interfaces/confounds.py", line 84, in _run_interface
    "session": [self.inputs.entities['session']],
KeyError: 'session'

**Comment by SiegfriedWagner** [comment]
We are currently refactoring fmridenoise (most recent version is available in branch dev) and problems with bids data structures (like session existence) are addressed. It's hard to estimate when we will finish refactoring (currently only quality measures between subjects, quality measures between pipelines and functions responsible for creating reports needs refactoring)

**Comment by ortiztudelaJ** [comment]
Oh ok, I wasn't aware of that. Looking forward to the new version!
Good luck then! 
Javier.

**Comment by Tao-ZJU** [comment]
Hi @kbonna, I run the fmridenoise, but BidsGrabber errors occurred. 

The errors were: 
[error.txt](https://github.com/compneuro-ncu/fmridenoise/files/5076251/error.txt)

The crash file is: 

[crash-20200815-010858-xuxiaojun-BidsGrabber-57de1024-aa55-412b-b47f-5271893a062a.zip](https://github.com/compneuro-ncu/fmridenoise/files/5076261/crash-20200815-010858-xuxiaojun-BidsGrabber-57de1024-aa55-412b-b47f-5271893a062a.zip)

The output space of fmriprep is MNI152NLin6Asym, not the MNI152NLin2009cAsym. Does this matter? Thank you!
