### ISSUE TITLE
FileNotFoundError: ICA-Aroma file not found

### ISSUE THREAD

**Issue by kfinc** [nbraingroup/fmridenoise#30]
Issue raised via Neurostars:
https://neurostars.org/t/fmridenoise-error-looking-for-ica-aroma-file/5058

Is this possible that BIDSGrabber fails because of the lack of ICA-AROMA files?

We should add more conditionals for situations when the user doesn't have/want to use AROMA files. There are three possibilities:

1. User doesn't have ICA-AROMA files but wants to use all other pipelines
2. User wants to use selected pipeline(s) not using ICA-AROMA files
3. User just don't want to use ICA-AROMA denoising but has ICA-AROMA files

Did I miss something?

**Comment by kfinc** [comment]
I've added optional `--use-aroma` flag for users who have ICA-AROMA files and wants to use them. Default is `False`.

**Comment by wiheto** [comment]
I ran into this bug too and still got an error with the current fix. I've submitted a PR which ignores selecting ica_aroma pipelines if `--use-aroma` is false.
