### ISSUE TITLE
cant seem to install fmridenoise

### ISSUE THREAD

**Issue by jandrushko** [nbraingroup/fmridenoise#42]
Hi I am struggling to install fmridenoise. I am hoping to run it on my post-fmriprep’d data but cant seem to successfully install it.

I have tried installing it two different ways:

sudo pip install fmridenoise --user
Collecting fmridenoise
Using cached https://files.pythonhosted.org/packages/d6/96/33ed5e5f6984643a924e6497d172c4b078fae1cd8ee36b3d2733e1aa0605/fmridenoise-0.1.5.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File “”, line 1, in
File “/tmp/pip-build-WhlwqE/fmridenoise/setup.py”, line 11
def get_requirements() -> list:
^
SyntaxError: invalid syntax

----------------------------------------

Command “python setup.py egg_info” failed with error code 1 in /tmp/pip-build-WhlwqE/fmridenoise/

and then I have also tried downloading the file, moving to the saved directory and running it this way:

python setup.py install --user
File “setup.py”, line 11
def get_requirements() -> list:
^
SyntaxError: invalid syntax

I am not sure what to do about these issues and I am not overly proficient at coding.

Any help is appreciated

**Comment by wiheto** [comment]
Hi. What is you python version? To get it, type:

`python --version`

I'm guessing it is python 2.x.x something?

**Comment by jandrushko** [comment]
Hello, thank you for your response. My python version is 2.7.15+

**Comment by wiheto** [comment]
fmridenoise only works with python 3 I am afraid. You will have to install that to get it working.

**Comment by jandrushko** [comment]
Ah, I just installed it through anaconda with python 3.7 and it worked. Thank you so much!
